PREFIX  bibo: <http://purl.org/ontology/bibo/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
SELECT ?pub {
    SELECT ?pub 
    WHERE{
        ?pub vivo:relatedBy ?authorship.
        ?pub a bibo:AcademicArticle .
        ?authorship a vivo:Authorship .
    }GROUP BY ?pub
    HAVING(COUNT(DISTINCT(?authorship)) > 50)
}
LIMIT 1